In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import psycopg2
from scipy.stats import ks_2samp
from scipy.stats import mannwhitneyu
from scipy.stats import gaussian_kde
from scipy import integrate
from sklearn.neighbors import KernelDensity
from scipy.stats import entropy
import scipy.stats
import seaborn as sns
import warnings
import tableone
warnings.filterwarnings("ignore")

In [2]:
data_mimic = pd.read_csv('E:/MyProject/ICU-labtest-range-global-study/datasets/processed data/MIMIC-data.csv')
data_aumc = pd.read_csv('E:/MyProject/ICU-labtest-range-global-study/datasets/processed data/AUMC-data.csv')
data_eicu = pd.read_csv('E:/MyProject/ICU-labtest-range-global-study/datasets/processed data/eCRD-data.csv')
data_plagh = pd.read_csv('E:/MyProject/ICU-labtest-range-global-study/datasets/processed data/PLAGH-data.csv')
data_HJ23 = pd.read_csv('E:/MyProject/ICU-labtest-range-global-study/datasets/processed data/HJ23-data.csv')

In [3]:
#adjust the unit of each labtest
#for plagh database
data_plagh['albumin_min']=data_plagh['albumin_min']/10
data_plagh['creatinine_max']=data_plagh['creatinine_max']/88.4
data_plagh['creatinine_min']=data_plagh['creatinine_min']/88.4
data_plagh['glucose_max']=data_plagh['glucose_max']*18.018
data_plagh['glucose_min']=data_plagh['glucose_min']*18.018
data_plagh['hemoglobin_min']=data_plagh['hemoglobin_min']/10
data_plagh['magnesium_max']=data_plagh['magnesium_max']/0.5
data_plagh['magnesium_min']=data_plagh['magnesium_min']/0.5
data_plagh['calcium_max']=data_plagh['calcium_max']/0.25
data_plagh['calcium_min']=data_plagh['calcium_min']/0.25

In [4]:
#adjust the unit of each labtest
#for AUMC
data_aumc['albumin_min']=data_aumc['albumin_min']/10
data_aumc['albumin_max']=data_aumc['albumin_max']/10
data_aumc['bilirubin_max']=data_aumc['bilirubin_max']/17.1
data_aumc['bilirubin_min']=data_aumc['bilirubin_min']/17.1
data_aumc['calcium_max']=data_aumc['calcium_max']/0.25
data_aumc['calcium_min']=data_aumc['calcium_min']/0.25
data_aumc['hemoglobin_max']=data_aumc['hemoglobin_max']/0.62
data_aumc['hemoglobin_min']=data_aumc['hemoglobin_min']/0.62
data_aumc['creatinine_max']=data_aumc['creatinine_max']/88.4
data_aumc['creatinine_min']=data_aumc['creatinine_min']/88.4
data_aumc['glucose_max']=data_aumc['glucose_max']*18.018
data_aumc['glucose_min']=data_aumc['glucose_min']*18.018
data_aumc['magnesium_max']=data_aumc['magnesium_max']/0.5
data_aumc['magnesium_min']=data_aumc['magnesium_min']/0.5
data_aumc['phosphate_max']=data_aumc['phosphate_max']/0.32
data_aumc['phosphate_min']=data_aumc['phosphate_min']/0.32

In [5]:
data_plagh['icu_los_hours']=data_plagh['icu_los_hours']*24
data_plagh['hospital_los_hours']=data_plagh['hospital_los_hours']*24

In [6]:
lab_ranges = {'ALBUMIN':[3.5, 5.5], 
              'BICARBONATE': [22,32],
              'BUN': [6,20],
              'CALCIUM': [8.4,10.3],
              'CREATININE': [0.4,1.1],
              'GLUCOSE':[70.0, 100.0],
              'HEMOGLOBIN': [11.2,15.7],
              'LACTATE': [0.5,2.0],
              'MAGNESIUM': [1.6,2.6],
              'PHOSPHATE': [2.7,4.5],
              'PLATELET': [150,400],
              'POTASSIUM': [3.3,5.1],
              'SODIUM': [133,145],
              'IONIZEDCALCIUM': [1.1, 1.35],
              'WBC': [3.5, 10.5]
             }

#define the obvious outlier ranges
lab_outlier_ranges = {'ALBUMIN':[0.2, 7], 
                      'BICARBONATE': [1,80],
                      'CALCIUM': [0.1,100],
                      'CREATININE': [0,30],
                      'GLUCOSE':[7, 1000.0],
                      'HEMOGLOBIN': [0.1,30],
                      'LACTATE': [0,30],
                      'MAGNESIUM': [0,50],
                      'PHOSPHATE': [0,100],
                      'PLATELET': [1,1200],
                      'POTASSIUM': [0,20],
                      'SODIUM': [50,300],
                      'IONIZEDCALCIUM': [0, 15],
                      'WBC': [0, 400]
                     }

lab_units = {
        'ALBUMIN': 'g/dL', 
        'BICARBONATE': 'mEq/L',
        'BUN': 'mEq/L',
        'CALCIUM': 'mg/dL',
        'CREATININE': 'mEq/L',
        'GLUCOSE': 'mg/dL',
        'HEMOGLOBIN': 'g/dL',
        'LACTATE': 'mmol/L',
        'MAGNESIUM': 'mmol/L',
        'PHOSPHATE': 'mg/dL',
        'PLATELET': 'K/uL',
        'POTASSIUM': 'mEq/L',
        'SODIUM':'mmol/L',
        'IONIZEDCALCIUM': 'mmol/L',
        'WBC': '10^3/uL'
       }

In [7]:
kinds=['_min','_max']
for kind in kinds:
    for l, u in iter(sorted(lab_units.items())):
        if (l.lower()+kind) not in data_plagh.columns.values:
            continue
        
        data_mimic.loc[data_mimic[(data_mimic[l.lower()+kind]<lab_outlier_ranges[l][0])|(data_mimic[l.lower()+kind]>lab_outlier_ranges[l][1])].index,
                       [l.lower()+kind]]=np.nan
        
        data_eicu.loc[data_eicu[(data_eicu[l.lower()+kind]<lab_outlier_ranges[l][0])|(data_eicu[l.lower()+kind]>lab_outlier_ranges[l][1])].index,
                       [l.lower()+kind]]=np.nan
        
        data_plagh.loc[data_plagh[(data_plagh[l.lower()+kind]<lab_outlier_ranges[l][0])|(data_plagh[l.lower()+kind]>lab_outlier_ranges[l][1])].index,
                       [l.lower()+kind]]=np.nan
        
        data_aumc.loc[data_aumc[(data_aumc[l.lower()+kind]<lab_outlier_ranges[l][0])|(data_aumc[l.lower()+kind]>lab_outlier_ranges[l][1])].index,
                       [l.lower()+kind]]=np.nan
        
        data_HJ23.loc[data_HJ23[(data_HJ23[l.lower()+kind]<lab_outlier_ranges[l][0])|(data_HJ23[l.lower()+kind]>lab_outlier_ranges[l][1])].index,
                       [l.lower()+kind]]=np.nan

In [8]:
#rename the ICUs
data_mimic['unittype'].replace(['MICU','EICU','KICU','RICU'],'MICU')

0         MICU
1         MICU
2         SICU
3         MICU
4         SICU
5         SICU
6          CCU
7         CSRU
8          CCU
9        TSICU
10        CSRU
11         CCU
12        MICU
13        CSRU
14         CCU
15         CCU
16         CCU
17        CSRU
18         CCU
19        MICU
20       TSICU
21        MICU
22        MICU
23        CSRU
24        CSRU
25        MICU
26         CCU
27        SICU
28         CCU
29       TSICU
         ...
38478     MICU
38479    TSICU
38480     MICU
38481     MICU
38482      CCU
38483     SICU
38484     MICU
38485     CSRU
38486     CSRU
38487     MICU
38488     MICU
38489     SICU
38490     SICU
38491     MICU
38492     CSRU
38493     MICU
38494      CCU
38495     MICU
38496     SICU
38497     MICU
38498     SICU
38499      CCU
38500     MICU
38501     CSRU
38502      CCU
38503     MICU
38504    TSICU
38505     MICU
38506     CSRU
38507     SICU
Name: unittype, Length: 38508, dtype: object

In [9]:
l_all=[data_mimic,data_eicu,data_plagh,data_aumc,data_HJ23]
#rename the ICUs
for i in range(0,len(l_all)):
    if 'unittype' in l_all[i].columns.values:
        l_all[i]['unittype'].replace(['MICU','EICU','KICU','RICU'],'MICU',inplace=True)
        l_all[i]['unittype'].replace(['Neuro ICU','NSICU'],'NICU',inplace=True)
        l_all[i]['unittype'].replace(['CCU','Cardiac ICU','CSRU','CSICU','CTICU','CCU-CTICU'],'CCU',inplace=True)
        l_all[i]['unittype'].replace(['SICU','TSICU','Med-Surg ICU','ICU','TICU'],'SICU',inplace=True)
        print(l_all[i]['unittype'].unique())
    l_all[i]['gender'].replace(['F','female','Female'],0,inplace=True)
    l_all[i]['gender'].replace(['M','memale','male'],1,inplace=True) 
    l_all[i]['gender']=pd.to_numeric(l_all[i]['gender'],errors='coerce')
    print(l_all[i]['gender'].unique())

['MICU' 'SICU' 'CCU']
[1 0]
['SICU' 'MICU' 'NICU' 'CCU']
[0 1]
['SICU' 'CCU' 'MICU' 'NICU']
[1 0]
[ 0.  1. nan]
['MICU' 'SICU']
[ 1.  0. nan]

In [10]:
l_all[0].columns.values

array(['subject_id', 'hadm_id', 'icustay_id', 'gender', 'age',
       'ethnicity', 'icu_los_hours', 'icu_expire_flag', 'albumin_min',
       'albumin_max', 'bilirubin_min', 'bilirubin_max', 'bicarbonate_min',
       'bicarbonate_max', 'creatinine_min', 'creatinine_max',
       'glucose_min', 'glucose_max', 'hemoglobin_min', 'hemoglobin_max',
       'lactate_min', 'lactate_max', 'platelet_min', 'platelet_max',
       'potassium_min', 'potassium_max', 'sodium_min', 'sodium_max',
       'magnesium_min', 'magnesium_max', 'phosphate_min', 'phosphate_max',
       'bun_min', 'bun_max', 'wbc_min', 'wbc_max', 'calcium_min',
       'calcium_max', 'ionizedcalcium_min', 'ionizedcalcium_max',
       'unittype', 'vent_duration_hours', 'crrt_duration_hours',
       'hospital_los_hours', 'admission_type'], dtype=object)

In [11]:
count_n=['gender','icu_expire_flag']

count_notnan=['gender','icu_expire_flag',
              'unittype','admission_type',
            'albumin_min','albumin_max',
              'bilirubin_min', 'bilirubin_max', 
              'bicarbonate_min','bicarbonate_max',
              'creatinine_min', 'creatinine_max',
              'glucose_min', 'glucose_max',
              'hemoglobin_min', 'hemoglobin_max',
              'lactate_min', 'lactate_max', 
              'platelet_min', 'platelet_max',
              'potassium_min', 'potassium_max',
              'sodium_min', 'sodium_max',
              'magnesium_min', 'magnesium_max',
              'phosphate_min', 'phosphate_max',
              'bun_min', 'bun_max', 
              'wbc_min', 'wbc_max',
              'calcium_min','calcium_max',
              'ionizedcalcium_min', 'ionizedcalcium_max',
              'vent_duration_hours', 'crrt_duration_hours']

cats=['unittype','admission_type']

continous=['icu_los_hours','hospital_los_hours',
          'albumin_min','albumin_max',
          'bilirubin_min', 'bilirubin_max', 
          'bicarbonate_min','bicarbonate_max',
          'creatinine_min', 'creatinine_max',
          'glucose_min', 'glucose_max',
          'hemoglobin_min', 'hemoglobin_max',
          'lactate_min', 'lactate_max', 
          'platelet_min', 'platelet_max',
          'potassium_min', 'potassium_max',
          'sodium_min', 'sodium_max',
          'magnesium_min', 'magnesium_max',
          'phosphate_min', 'phosphate_max',
          'bun_min', 'bun_max', 
          'wbc_min', 'wbc_max',
          'calcium_min','calcium_max',
          'ionizedcalcium_min', 'ionizedcalcium_max',
          'vent_duration_hours', 'crrt_duration_hours']

divide_expired=['icu_los_hours','hospital_los_hours','age','vent_duration_hours', 'crrt_duration_hours']

In [12]:
table=pd.DataFrame()
for icu_no in range(0,len(l_all)):
    table.loc['N',icu_no]=l_all[icu_no].shape[0]
    N=l_all[icu_no].shape[0]
    
    for item in count_n:
        if item in l_all[icu_no].columns.values:
            table.loc[item+'_1',icu_no]='%.0f'%(l_all[icu_no].loc[l_all[icu_no][item]==1,:].shape[0])\
            +'({}%)'.format('%.1f'%(l_all[icu_no].loc[l_all[icu_no][item]==1,:].shape[0]/l_all[icu_no].loc[l_all[icu_no][item].notnull(),:].shape[0]*100))
    
    for item in cats:
        if item in l_all[icu_no].columns.values:
            for cat in l_all[icu_no][item].unique():
                table.loc[item+'_'+str(cat),icu_no]='%.0f'%(l_all[icu_no].loc[l_all[icu_no][item]==cat,:].shape[0])\
                +'({}%)'.format('%.1f'%(l_all[icu_no].loc[l_all[icu_no][item]==cat,:].shape[0]/N*100))
                
    for item in divide_expired:
        if item in l_all[icu_no].columns.values:
            #survivals
            table.loc['N_'+item+'_0',icu_no]='%.0f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==0) & (l_all[icu_no][item].notnull()),:].shape[0])\
                +'({}%)'.format('%.1f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==0) & (l_all[icu_no][item].notnull()),:].shape[0]/l_all[icu_no].loc[(l_all[icu_no][item].notnull()),:].shape[0]*100))
            table.loc['Result_'+item+'_0',icu_no]='%.2f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==0) & (l_all[icu_no][item].notnull()),:][item].describe()['50%'])\
            +' [{}-{}]'.format('%.2f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==0) & (l_all[icu_no][item].notnull()),:][item].describe()['25%']),'%.2f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==0) & (l_all[icu_no][item].notnull()),:][item].describe()['75%']))
            
            #expired
            table.loc['N_'+item+'_1',icu_no]='%.0f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==1) & (l_all[icu_no][item].notnull()),:].shape[0])\
                +'({}%)'.format('%.1f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==1) & (l_all[icu_no][item].notnull()),:].shape[0]/l_all[icu_no].loc[(l_all[icu_no][item].notnull()),:].shape[0]*100))
            table.loc['Result_'+item+'_1',icu_no]='%.2f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==1) & (l_all[icu_no][item].notnull()),:][item].describe()['50%'])\
            +' [{}-{}]'.format('%.2f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==1) & (l_all[icu_no][item].notnull()),:][item].describe()['25%']),'%.2f'%(l_all[icu_no].loc[(l_all[icu_no]['icu_expire_flag']==1) & (l_all[icu_no][item].notnull()),:][item].describe()['75%']))
    
    for item in count_notnan:
        if item in l_all[icu_no].columns.values:
            table.loc['Missing_'+item,icu_no]='%.0f'%(l_all[icu_no].loc[l_all[icu_no][item].isnull(),:].shape[0])\
            +'({}%)'.format('%.1f'%(l_all[icu_no].loc[l_all[icu_no][item].isnull(),:].shape[0]/N*100))
    
    for item in continous:
        if item in l_all[icu_no].columns.values:
            table.loc['Result_'+item,icu_no]='%.2f'%(l_all[icu_no][item].describe()['50%'])\
            +' [{}-{}]'.format('%.2f'%(l_all[icu_no][item].describe()['25%']),'%.2f'%(l_all[icu_no][item].describe()['75%']))
table

,0,1,2,3,4
N,38508,200764,63534,20127,4840
gender_1,21793(56.6%),108464(54.0%),38171(60.1%),12807(65.2%),3121(64.5%)
icu_expire_flag_1,2919(7.6%),10936(5.4%),3743(5.9%),1929(9.6%),721(14.9%)
unittype_MICU,13634(35.4%),17459(8.7%),8633(13.6%),NaN,3475(71.8%)
unittype_SICU,11595(30.1%),125326(62.4%),8392(13.2%),NaN,1365(28.2%)
unittype_CCU,13279(34.5%),43528(21.7%),27939(44.0%),NaN,NaN
admission_type_EMERGENCY,31045(80.6%),NaN,NaN,NaN,4633(95.7%)
admission_type_ELECTIVE,6039(15.7%),NaN,NaN,NaN,207(4.3%)
admission_type_URGENT,1077(2.8%),NaN,NaN,NaN,NaN
admission_type_nan,0(0.0%),NaN,NaN,NaN,NaN
N_icu_los_hours_0,35587(92.4%),189828(94.6%),59791(94.1%),18198(90.4%),4119(85.1%)
Result_icu_los_hours_0,49.00 [28.10-93.30],37.00 [19.00-70.00],94.83 [45.91-168.24],24.00 [20.00-67.00],94.70 [50.40-186.55]
N_icu_los_hours_1,2919(7.6%),10936(5.4%),3743(5.9%),1929(9.6%),721(14.9%)
Result_icu_los_hours_1,90.40 [40.15-199.40],41.00 [13.00-110.00],116.67 [41.86-271.02],70.00 [26.00-194.00],100.20 [32.90-263.40]
N_hospital_los_hours_0,35244(92.4%),189828(94.6%),59791(94.1%),NaN,4086(85.1%)
Result_hospital_los_hours_0,7.00 [4.21-11.97],135.10 [71.75-242.47],288.56 [162.97-472.10],NaN,305.65 [168.30-616.05]
N_hospital_los_hours_1,2917(7.6%),10936(5.4%),3743(5.9%),NaN,715(14.9%)
Result_hospital_los_hours_1,4.65 [1.76-9.94],81.04 [30.13-198.73],215.12 [75.15-499.80],NaN,169.70 [52.80-430.75]
N_age_0,35589(92.4%),189828(94.6%),59790(94.1%),NaN,4119(85.1%)
Result_age_0,65.10 [51.90-77.40],65.00 [52.00-76.00],56.46 [45.63-66.24],NaN,62.00 [48.00-72.00]
N_age_1,2919(7.6%),10936(5.4%),3743(5.9%),NaN,721(14.9%)
Result_age_1,73.40 [60.00-82.50],71.00 [59.00-80.00],64.39 [51.73-75.27],NaN,68.00 [58.00-76.00]
N_vent_duration_hours_0,16552(87.0%),57874(87.0%),NaN,NaN,1389(71.0%)
Result_vent_duration_hours_0,16.50 [5.87-63.50],28.53 [11.52-74.07],NaN,NaN,93.90 [25.30-247.30]
N_vent_duration_hours_1,2470(13.0%),8634(13.0%),NaN,NaN,566(29.0%)
Result_vent_duration_hours_1,67.62 [24.00-177.88],40.42 [12.30-106.26],NaN,NaN,94.00 [32.00-271.50]
N_crrt_duration_hours_0,333(51.9%),NaN,NaN,NaN,NaN
Result_crrt_duration_hours_0,95.00 [44.67-169.58],NaN,NaN,NaN,NaN
N_crrt_duration_hours_1,309(48.1%),NaN,NaN,NaN,NaN
Result_crrt_duration_hours_1,59.20 [19.50-151.08],NaN,NaN,NaN,NaN
...,...,...,...,...,...
Result_glucose_min,110.00 [93.00-133.00],109.00 [92.00-135.00],118.38 [95.86-148.47],113.51 [95.50-133.33],118.00 [96.00-146.00]
Result_glucose_max,145.00 [116.00-184.00],147.00 [118.00-198.00],126.67 [100.00-162.88],183.78 [153.15-214.41],150.00 [118.00-198.00]
Result_hemoglobin_min,10.30 [8.90-11.90],11.00 [9.10-12.70],12.40 [10.70-13.90],10.00 [8.71-11.61],10.70 [8.90-12.50]
Result_hemoglobin_max,11.30 [10.10-12.60],12.40 [10.60-14.00],NaN,11.94 [10.97-13.23],11.40 [9.70-13.20]
Result_lactate_min,1.50 [1.10-2.20],1.40 [1.00-2.20],NaN,1.30 [0.90-2.00],1.66 [1.26-2.34]
Result_lactate_max,2.10 [1.40-3.30],2.00 [1.30-3.60],nan [nan-nan],2.10 [1.30-3.40],1.97 [1.45-2.94]
Result_platelet_min,189.00 [135.00-252.00],188.00 [138.00-244.00],196.00 [153.00-243.00],156.00 [110.00-214.00],180.00 [129.00-240.00]
Result_platelet_max,208.00 [157.00-270.00],222.00 [170.00-285.00],NaN,192.00 [149.00-248.00],196.00 [146.00-260.00]
Result_potassium_min,3.80 [3.50-4.10],3.80 [3.40-4.20],3.82 [3.58-4.10],3.80 [3.50-4.10],3.80 [3.44-4.10]
Result_potassium_max,4.30 [3.90-4.80],4.30 [4.00-4.80],3.93 [3.66-4.22],4.50 [4.20-4.80],4.15 [3.80-4.61]
Result_sodium_min,138.00 [135.00-140.00],137.00 [134.00-139.00],140.40 [137.80-142.80],137.00 [134.00-139.00],137.70 [135.00-140.00]
Result_sodium_max,140.00 [137.00-142.00],140.00 [137.00-142.00],141.10 [138.60-143.50],141.00 [139.00-144.00],140.20 [138.00-143.00]
Result_magnesium_min,1.90 [1.70-2.10],1.80 [1.60-2.00],1.70 [1.54-1.84],1.60 [1.40-2.00],1.93 [1.69-2.18]
Result_magnesium_max,2.10 [1.90-2.30],2.00 [1.80-2.30],1.74 [1.58-1.88],2.00 [1.60-2.40],1.99 [1.75-2.24]
Result_phosphate_min,3.20 [2.60-3.90],3.20 [2.40-4.00],nan [nan-nan],2.81 [2.19-3.44],3.50 [2.80-4.30]
Result_phosphate_max,3.50 [2.90-4.30],3.60 [2.90-4.50],nan [nan-nan],3.75 [2.81-4.38],3.50 [2.80-4.30]
Result_bun_min,16.00 [11.00-26.00],17.00 [11.00-27.00],NaN,6.10 [4.30-8.90],18.70 [13.10-30.80]
Result_bun_max,18.00 [13.00-29.00],21.00 [14.00-34.00],NaN,6.60 [4.70-9.90],21.00 [14.50-35.00]
Result_wbc_min,10.00 [7.40-13.30],8.90 [6.60-12.10],9.03 [6.48-12.46],11.20 [8.50-14.50],10.55 [7.71-14.28]
Result_wbc_max,11.50 [8.50-15.60],11.70 [8.53-16.30],9.74 [6.74-13.40],13.90 [10.70-17.80],12.27 [8.74-17.07]
Result_calcium_min,8.20 [7.60-8.70],8.30 [7.70-8.70],8.64 [8.16-9.08],7.60 [7.20-8.40],8.10 [7.50-8.70]
Result_calcium_max,8.40 [8.00-8.90],8.90 [8.40-9.30],8.72 [8.32-9.12],8.00 [7.60-8.40],8.20 [7.60-8.80]
Result_ionizedcalcium_min,1.07 [1.01-1.12],4.32 [3.40-4.68],1.13 [1.09-1.17],1.10 [1.00-1.20],1.11 [1.04-1.18]
Result_ionizedcalcium_max,1.07 [1.01-1.12],4.32 [3.40-4.68],NaN,1.10 [1.00-1.20],1.11 [1.04-1.18]
Result_vent_duration_hours,19.00 [6.50-82.00],29.63 [11.62-78.37],NaN,NaN,93.90 [27.75-255.95]
Result_crrt_duration_hours,77.45 [31.06-163.88],NaN,NaN,NaN,NaN
unittype_NICU,NaN,14451(7.2%),18570(29.2%),NaN,NaN
admission_type_outpatient,NaN,NaN,29400(46.3%),NaN,NaN
admission_type_emergency,NaN,NaN,34113(53.7%),NaN,NaN
admission_type_transfer,NaN,NaN,21(0.0%),NaN,NaN

In [13]:
table.to_csv('table1.csv',index=True)