In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
from tqdm import tqdm
from tableone import TableOne
import datetime
import time
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size':20})
%matplotlib inline
plt.style.use('ggplot')
import warnings
warnings.filterwarnings('ignore')


# Import libraries
import xgboost as xgb
import statsmodels.api as sm

In [2]:
data_mimic = pd.read_csv('../datasets/processed data/MIMIC-data.csv')
data_aumc = pd.read_csv('../datasets/processed data/AUMC-data.csv')
data_eicu = pd.read_csv('../datasets/processed data/eCRD-data.csv')
data_plagh = pd.read_csv('../datasets/processed data/PLAGH-data.csv')
data_HJ23 = pd.read_csv('../datasets/processed data/HJ23-data.csv')

In [3]:
# data_plagh['lactate_max']=np.nan
# data_eicu['admission_type']=np.nan
# data_HJ23['cardiac_surgery_flag']=np.nan

In [4]:
data_mimic_15=data_mimic.loc[(data_mimic['outcome_group']==1) | (data_mimic['outcome_group']==5),
                             ['gender','age_group','unittype','admission_type','cardiac_surgery_flag',
                              'sodium_max','creatinine_max','lactate_max','hemoglobin_min','outcome_group']]
data_mimic_15['database_flag']='MIMIC'

data_aumc_15=data_aumc.loc[(data_aumc['outcome_group']==1) | (data_aumc['outcome_group']==5),
                             ['gender','age_group','unittype','admission_type','cardiac_surgery_flag',
                              'sodium_max','creatinine_max','lactate_max','hemoglobin_min','outcome_group']]
data_aumc_15['database_flag']='AUMC'

data_eicu_15=data_eicu.loc[(data_eicu['outcome_group']==1) | (data_eicu['outcome_group']==5),
                             ['gender','age_group','unittype','admission_type','cardiac_surgery_flag',
                              'sodium_max','creatinine_max','lactate_max','hemoglobin_min','outcome_group']]
data_eicu_15['database_flag']='eICU'

data_plagh_15=data_plagh.loc[(data_plagh['outcome_group']==1) | (data_plagh['outcome_group']==5),
                             ['gender','age_group','unittype','admission_type','cardiac_surgery_flag',
                              'sodium_max','creatinine_max','lactate_max','hemoglobin_min','outcome_group']]
data_plagh_15['database_flag']='PLAGH'


data_HJ23_15=data_HJ23.loc[(data_HJ23['outcome_group']==1) | (data_HJ23['outcome_group']==5),
                             ['gender','age_group','unittype','admission_type','cardiac_surgery_flag',
                              'sodium_max','creatinine_max','lactate_max','hemoglobin_min','outcome_group']]
data_HJ23_15['database_flag']='HJ23'

In [5]:
bestvsworst_df=pd.concat([data_mimic_15,data_aumc_15,data_eicu_15,data_plagh_15,data_HJ23_15],ignore_index=True)
bestvsworst_df

,gender,age_group,unittype,admission_type,cardiac_surgery_flag,sodium_max,creatinine_max,lactate_max,hemoglobin_min,outcome_group,database_flag
0,1,"(39, 49]",MICU,EMERGENCY,0.0,138.0,1.40,2.70,12.9,5.0,MIMIC
1,0,"(69, 79]",CSRU,ELECTIVE,1.0,138.0,0.80,NaN,8.5,1.0,MIMIC
2,0,"(59, 69]",MICU,EMERGENCY,0.0,142.0,0.60,NaN,NaN,1.0,MIMIC
3,1,"(17, 39]",CCU,EMERGENCY,0.0,139.0,0.90,NaN,14.1,1.0,MIMIC
4,1,"(69, 79]",CSRU,ELECTIVE,1.0,141.0,1.00,NaN,8.6,1.0,MIMIC
5,1,"(69, 79]",MICU,EMERGENCY,0.0,133.0,0.70,1.50,NaN,5.0,MIMIC
6,1,"(79, 300]",MICU,EMERGENCY,0.0,140.0,1.20,NaN,12.0,1.0,MIMIC
7,1,"(69, 79]",CSRU,EMERGENCY,1.0,138.0,1.00,NaN,9.2,1.0,MIMIC
8,1,"(59, 69]",MICU,EMERGENCY,0.0,143.0,0.80,NaN,9.9,1.0,MIMIC
9,1,"(69, 79]",MICU,EMERGENCY,0.0,133.0,0.50,NaN,6.9,1.0,MIMIC
10,1,"(79, 300]",CSRU,ELECTIVE,1.0,140.0,1.30,2.30,10.6,1.0,MIMIC
11,1,"(79, 300]",MICU,EMERGENCY,0.0,NaN,NaN,NaN,NaN,1.0,MIMIC
12,1,"(39, 49]",CCU,EMERGENCY,0.0,139.0,1.10,NaN,13.2,1.0,MIMIC
13,0,"(39, 49]",SICU,EMERGENCY,0.0,138.0,0.50,NaN,12.5,5.0,MIMIC
14,0,"(39, 49]",CSRU,ELECTIVE,1.0,146.0,0.60,NaN,7.7,1.0,MIMIC
15,0,"(79, 300]",CSRU,EMERGENCY,1.0,137.0,1.20,NaN,8.4,1.0,MIMIC
16,1,"(69, 79]",CCU,EMERGENCY,0.0,134.0,0.70,1.70,13.3,1.0,MIMIC
17,1,"(39, 49]",CCU,EMERGENCY,0.0,141.0,0.90,NaN,11.7,1.0,MIMIC
18,1,"(17, 39]",MICU,EMERGENCY,0.0,136.0,1.20,3.50,15.2,5.0,MIMIC
19,1,"(59, 69]",SICU,EMERGENCY,0.0,140.0,8.30,NaN,11.4,1.0,MIMIC
20,1,"(69, 79]",CSRU,EMERGENCY,1.0,139.0,1.10,NaN,9.2,1.0,MIMIC
21,0,"(17, 39]",MICU,EMERGENCY,0.0,139.0,5.30,NaN,7.3,1.0,MIMIC
22,1,"(79, 300]",MICU,EMERGENCY,0.0,144.0,1.00,NaN,9.5,1.0,MIMIC
23,1,"(17, 39]",TSICU,EMERGENCY,0.0,141.0,0.80,NaN,13.3,1.0,MIMIC
24,1,"(17, 39]",MICU,EMERGENCY,0.0,NaN,NaN,NaN,NaN,1.0,MIMIC
25,1,"(49, 59]",SICU,ELECTIVE,0.0,143.0,0.80,NaN,13.8,1.0,MIMIC
26,1,"(39, 49]",CSRU,ELECTIVE,1.0,136.0,0.90,NaN,9.7,1.0,MIMIC
27,1,"(79, 300]",MICU,EMERGENCY,0.0,142.0,1.60,15.30,5.0,5.0,MIMIC
28,1,"(39, 49]",CCU,EMERGENCY,0.0,141.0,0.90,NaN,12.7,1.0,MIMIC
29,1,"(59, 69]",CCU,EMERGENCY,0.0,145.0,0.90,NaN,13.4,1.0,MIMIC
...,...,...,...,...,...,...,...,...,...,...,...
78800,0,"(59, 69]",MICU,EMERGENCY,0.0,135.4,0.50,1.78,14.9,1.0,HJ23
78801,1,"(79, 300]",SICU,EMERGENCY,0.0,140.0,2.53,3.41,10.7,5.0,HJ23
78802,1,"(39, 49]",MICU,EMERGENCY,0.0,142.0,3.23,NaN,12.5,1.0,HJ23
78803,1,"(69, 79]",MICU,EMERGENCY,0.0,143.0,1.02,NaN,14.1,1.0,HJ23
78804,1,"(69, 79]",MICU,EMERGENCY,0.0,146.0,1.88,NaN,7.1,1.0,HJ23
78805,0,"(69, 79]",MICU,EMERGENCY,0.0,145.0,7.53,2.41,7.6,5.0,HJ23
78806,0,"(39, 49]",MICU,EMERGENCY,0.0,138.3,0.42,1.14,10.9,1.0,HJ23
78807,1,"(79, 300]",MICU,EMERGENCY,0.0,140.6,0.95,2.17,11.6,1.0,HJ23
78808,1,"(69, 79]",MICU,EMERGENCY,0.0,150.0,1.41,1.72,12.9,5.0,HJ23
78809,1,"(49, 59]",MICU,EMERGENCY,0.0,132.0,NaN,4.03,12.4,5.0,HJ23
78810,1,"(59, 69]",SICU,EMERGENCY,0.0,153.0,2.43,9.28,9.9,1.0,HJ23
78811,1,"(17, 39]",MICU,EMERGENCY,0.0,141.4,NaN,1.24,14.6,1.0,HJ23
78812,0,"(49, 59]",MICU,EMERGENCY,0.0,141.0,1.46,NaN,15.5,1.0,HJ23
78813,1,"(59, 69]",MICU,EMERGENCY,0.0,153.0,1.43,4.84,14.3,5.0,HJ23
78814,1,"(39, 49]",MICU,EMERGENCY,0.0,138.0,0.85,1.10,13.1,1.0,HJ23
78815,1,"(39, 49]",MICU,EMERGENCY,0.0,158.8,2.83,23.00,13.9,5.0,HJ23
78816,0,"(17, 39]",MICU,EMERGENCY,0.0,142.7,0.68,1.44,11.8,1.0,HJ23
78817,0,"(69, 79]",MICU,EMERGENCY,0.0,144.0,0.86,NaN,NaN,5.0,HJ23
78818,0,"(49, 59]",SICU,EMERGENCY,0.0,136.0,2.13,1.90,10.0,1.0,HJ23
78819,0,"(69, 79]",SICU,EMERGENCY,0.0,136.1,0.39,1.32,9.7,1.0,HJ23
78820,1,"(59, 69]",MICU,EMERGENCY,0.0,142.0,5.50,2.59,14.3,5.0,HJ23
78821,0,"(69, 79]",MICU,EMERGENCY,0.0,128.0,0.55,2.50,11.7,5.0,HJ23
78822,1,"(59, 69]",MICU,EMERGENCY,0.0,148.1,1.21,1.29,11.5,1.0,HJ23
78823,1,"(49, 59]",MICU,EMERGENCY,0.0,139.0,5.90,1.85,11.1,1.0,HJ23
78824,0,"(69, 79]",MICU,EMERGENCY,0.0,140.6,1.53,2.36,8.3,1.0,HJ23
78825,1,"(49, 59]",MICU,EMERGENCY,0.0,140.0,2.87,10.48,6.2,5.0,HJ23
78826,0,"(59, 69]",MICU,EMERGENCY,0.0,155.3,1.60,3.77,9.4,5.0,HJ23
78827,1,"(17, 39]",MICU,EMERGENCY,0.0,138.3,0.68,2.72,15.5,1.0,HJ23
78828,1,"(49, 59]",SICU,EMERGENCY,0.0,142.0,0.45,1.49,8.4,1.0,HJ23
78829,1,"(17, 39]",MICU,EMERGENCY,0.0,136.3,0.53,1.48,7.7,1.0,HJ23

In [6]:
for column in bestvsworst_df.columns.values:
    print(column)
    print(bestvsworst_df[column].unique())

gender
[1 0 nan '1' '0' 'U']
age_group
['(39, 49]' '(69, 79]' '(59, 69]' '(17, 39]' '(79, 300]' '(49, 59]']
unittype
['MICU' 'CSRU' 'CCU' 'SICU' 'TSICU' 'SICU&MICU' 'Med-Surg ICU' 'CTICU'
 'NICU' 'CCU-CTICU' 'CSICU' 'NSICU' 'EICU' 'RICU' 'TICU' 'KICU']
admission_type
['EMERGENCY' 'ELECTIVE' nan]
cardiac_surgery_flag
[0. 1.]
sodium_max
[138.  142.  139.  141.  133.  140.  143.    nan 146.  137.  134.  136.
 144.  145.  147.  153.  124.  135.  150.  120.  149.  129.  132.  148.
 158.  131.  164.  130.  155.  160.  126.  156.  125.  151.  163.  127.
 128.  152.  154.  121.  157.  162.  122.  167.  159.  175.  166.  169.
 119.  161.  114.  165.  123.  180.  118.  116.  170.  117.  168.  173.
 143.8 143.2 139.7 141.9 138.4 183.  139.4 142.8 136.4 146.9 144.2 138.6
 108.  141.7 140.6 146.2 146.7 145.4 136.7 144.7 142.5 152.9 134.9 152.5
 151.4 142.4 139.3 149.6 182.  157.2 144.5 136.2 140.3 143.1 141.6 140.5
 142.1 153.7 150.6 145.1 178.  148.3 172.  177.  174.  142.2 140.9 139.5
 141.3 141.4 137.5 135.4 139.9 136.1 172.4 128.7 138.3 136.8 140.4 132.1
 138.9 137.1 138.1 183.2 138.7 138.8 144.3 136.9 142.9 134.5 136.3 139.6
 141.8 137.4 135.6 139.2 136.5 144.1 140.7 143.5 139.1 140.1 140.8 140.2
 131.1 133.6 141.5 142.3 143.3 123.2 137.2 130.4 125.8 137.7 141.2 144.6
 144.9 138.5 133.3 137.3 138.2 146.5 131.9 110.  101.  176.  105.  152.8
 179.  113.  107.  115.  112.  111.  181.  171.  109.  144.8 143.9 133.9
 147.1 133.7 135.2 134.7 148.8 134.6 156.3 131.3 137.6 142.7 135.8 142.6
 145.6 149.7 149.3 149.2 133.5 145.8 139.8 153.2 146.6 124.1 147.9 131.4
 141.1 132.3 137.9 135.1 144.4 143.6 145.5 143.4 150.8 134.2 135.5 147.8
 143.7 130.3 132.5 132.2 133.8 132.6 158.3 132.8 145.3 148.2 145.7 148.4
 146.1 133.1 146.8 136.6 145.9 146.3 150.5 148.1 134.8 149.5 159.1 162.2
 150.3 133.2 135.7 130.8 156.2 130.2 129.8 129.9 153.3 128.8 126.9 124.8
 149.9 125.7 126.8 134.4 130.9 150.2 148.9 154.3 120.4 127.8 133.4 134.1
 151.1 137.8 130.5 127.5 131.2 132.4 129.3 134.3 127.9 146.4 161.1 131.5
 153.5 148.5 124.5 155.9 129.1 157.6 135.3 127.7 150.7 122.7 129.2 129.4
 154.1 145.2 162.8 152.3 121.4 150.1 147.3 131.7 147.7 147.6 147.5 155.8
 132.9 129.6 166.3 131.8 159.9 151.6 132.7 161.8 129.7 135.9 158.1 148.6
 130.1 152.2 169.1 151.9 147.2 130.7 147.4 129.5 152.1 124.6 154.4 177.8
 130.6 151.7 160.7 152.7 156.6 128.9 124.9 120.9 126.3 148.7 119.6 149.4
 126.1 123.4 156.1 125.5 155.5 149.8 167.9 149.1 170.1 126.7 153.6 155.3
 151.5 131.6 123.8 155.1 128.4 192.  156.7 159.8 127.2 116.3 126.4 167.5
 120.2 127.3 128.6 170.7 124.2 158.6 150.4 123.7 125.6 125.2 163.9 159.2
 127.4 122.2 153.4 150.9 162.1 182.8 154.7 161.6 164.8 126.5 128.5 119.8
 155.2 164.6 154.5 151.8 156.8 160.3 164.2 154.9 152.4 165.9 154.2 163.3
 126.2 118.9 157.3 175.1 157.9 163.8 175.7 151.2 127.1 163.4 153.1 123.5
 121.3 157.8 158.5 153.9 168.8 122.4 166.7 165.5 154.6 157.7 157.4 120.8
 154.8 169.6 113.8 152.6 122.9 160.4 156.4 153.8 165.7 122.5 157.5 128.2
 161.2 159.7 125.1 155.7 128.3 155.4 159.6 151.3 124.4 160.2 127.6 175.9
 161.9 163.1 166.8 160.8 125.4 123.3 105.5 199.  158.8]
creatinine_max
[ 1.4   0.8   0.6  ...  7.04 10.56  6.15]
lactate_max
[ 2.7    nan  1.5   2.3   1.7   3.5  15.3   1.    2.6   4.4   2.5   0.9
  0.5  15.6   3.9   1.4   2.1  13.8   2.2  11.8  17.7   4.6   2.4   5.7
  4.9   7.7   5.   12.5   1.8   3.2   2.9   4.5   5.2   1.2   8.    6.3
  2.    4.1   5.9   0.59  3.8   5.3   1.3  14.   10.5   9.    3.7   1.9
  0.8   6.6   9.4   2.8   5.8  11.3   9.6   1.6   7.9   7.4   5.1  17.5
 14.9   4.    8.9   8.3  15.4   6.2  18.3   3.3   8.4  21.3   3.6  29.3
 10.7  16.1   3.1  12.9  11.5   4.7   6.9   9.9   9.7  17.2  20.8   7.5
 19.    5.4  13.4   0.7   4.2  12.8  10.9   6.8   6.4   1.1   7.2   4.3
 16.6  15.1  19.7  10.8   3.    6.5  10.6   8.8   7.6  12.    6.1  22.7
 12.4  15.9   7.1  10.2  10.    3.4   6.7   8.1  12.6   0.6   9.8  16.3
 16.7  11.9  21.    5.5   1.79  8.6  13.3  10.3  13.5   7.8   3.45  9.1
 10.1  26.3  11.    5.6  12.7  16.4   6.   17.3  14.7   9.3  16.5   7.3
 18.7  15.   11.1  14.2  14.6  15.5   4.8  11.4  12.3  14.4  16.8   9.2
 12.2  15.8  15.2  15.7  19.6  16.9  22.4   8.5  11.2  26.4   9.5   7.
 24.   26.9  19.5   8.2  20.1   0.4  21.6  17.4  14.5  28.8  14.8  27.
 13.2  14.1  11.7   0.94 17.8  17.1  22.6  13.6   6.07  8.7  10.4  11.6
 19.1  21.4  18.4  23.5  14.3  12.1  13.9  13.7  20.5  20.7  17.9  13.
 18.1  18.6  19.3  21.2  20.2  18.   26.   17.   29.   25.   22.    0.3
 20.   23.    0.   19.8  16.2  18.5  23.7  18.8  16.   28.   13.1  19.4
  0.2  24.8  23.2  19.9  21.1  22.1  24.3  20.6  27.4  22.5  23.1  23.4
 22.3  20.3  19.2  18.9  28.3  22.2  27.3  17.6  21.9   0.1  21.7  21.8
 18.2  24.1  26.2  18.42  1.18  1.56  1.19  7.03  2.95 15.44 10.83  1.09
  1.31  3.37  4.85  2.43  8.92  1.23  6.67  1.49 13.21  1.59  4.31 17.14
  2.04  1.58 14.82  2.05  1.63  1.11  1.01  2.22  7.62  4.58  1.35 18.24
 13.09  2.53 11.84  2.61  2.88  1.15  1.98  1.21  1.36  2.01  3.71  1.27
  1.52  6.83  5.33  3.34  1.93  0.83  3.81  2.76 10.88  0.72  2.12  2.19
  0.88  1.53  0.73 10.51  5.85  2.49  2.64 14.94  0.92  2.69 18.79  5.83
  8.19  1.43  1.02  8.29  3.38  2.09  3.26  5.82  1.46  1.71  7.56  1.66
 14.48  7.68  2.77  3.59  1.86  2.98  5.93 14.73  3.66  3.42 13.61  3.61
  2.29  3.78  1.95  2.35  4.59  1.13  1.14  1.33  4.63  0.85  1.81  4.42
  2.02  1.91  2.36  1.62  2.46  2.07  3.23  6.76  3.75  2.86  2.14  3.53
  1.65  2.82  0.86  3.67  7.48 19.32 13.14  1.75  4.54  2.27  0.99  1.05
 13.34  6.14  2.23  4.39  2.84  3.74  1.54  1.78  4.43  2.65  1.22  1.89
  2.15 13.83  2.79  2.68  6.95  2.67 14.63  2.24  7.46  8.96 10.97  3.03
  1.44  5.14  1.76  1.39  1.16  6.98 14.95  8.31  8.64  3.05 17.84  3.04
  1.29  2.37  9.19  1.88  5.38 13.73  9.32  1.08 20.9  24.7  25.9  25.8
 24.4  26.8  23.6   3.29  1.99  0.89 24.6   9.92  9.29  6.39  7.72  4.69
  1.12  2.26  3.41  5.01  2.32  2.94  3.14  3.91  2.21  1.37  9.63  2.52
  2.75  2.03  1.34  0.96  6.22  4.89  3.93  1.38 11.75  3.06  0.82  3.24
  8.67  2.47  8.59  2.55  0.54  7.64  0.95  1.83  8.89  6.65  4.99  2.42
  6.46  3.43  4.03  1.68  2.66  1.24 14.74  4.37  1.57  1.47  4.32  2.28
  8.57  0.87  4.45  7.65  8.79  3.33  2.58  0.57  2.59  3.28  9.68  2.63
  1.64  2.83  1.07  3.86  1.51  8.81  1.72  6.86  2.13  7.11  5.91  0.65
  4.19  4.16  1.32  1.74 27.6   1.48 14.52 12.98 12.08 17.41  3.15  2.38
  0.79  8.47  3.47  0.77  5.92  7.47 14.06  1.41  1.97  3.39  1.04  8.99
  4.72 22.9  22.8  29.6  28.5   0.75  1.84  7.23  2.74  3.73  8.88  2.48
  2.45 14.91 21.5  13.54  3.57 13.12  3.72  0.63  7.08 15.27 16.37  4.87
  4.24  0.58  0.64 16.07  0.76  2.34 29.5   8.17  1.17  3.21  0.84 18.54
  5.32  0.49  1.87  3.83  5.89  0.78  2.92 27.7   1.82  0.74  8.11 12.25
 10.96  0.93  5.48  3.16  1.94  6.75  1.06  0.71  3.65  5.63  9.89  5.42
  0.91 12.97 27.5  17.25  6.68  5.47  1.85  1.77  6.18  0.44 14.34  3.85
  5.13 11.72  6.24  4.96  3.36  2.25 11.92  4.94  1.92  5.61 23.3   8.72
 13.87 23.8  26.7   2.56  2.16  3.46 13.11 15.41 11.33  3.58  5.84  1.45
  6.13 27.18  7.76  6.85  0.56  8.34  7.79  1.42  7.12 14.01  5.51 11.18
  5.41  0.67  3.51 12.24 20.38  4.46  2.89  2.57  5.16 17.17  6.53 15.84
  2.78  0.66 12.15 19.92  6.09  9.52  1.69  2.33  7.99  4.74  5.76  0.47
  0.21 18.29  5.31  2.31  7.39  2.18  1.55  3.07  8.14  3.89 16.48  7.92
  2.71 11.51  9.36  8.91 12.99  3.55  6.94  2.17  2.08  8.44  8.56 12.88
  4.33  0.98  2.39  5.25  5.52  4.25 15.69  7.91  5.95  4.15  4.48  8.08
 17.26  5.36 25.6  12.06  4.01  5.65  3.35  1.25  6.37  5.02  6.82  7.95
  4.97  2.91 11.15  3.98  4.56  2.81  1.61  5.94  2.44  3.02 14.61  9.97
  3.76  4.41  1.28  6.66  3.18  0.04  3.63  4.95  2.11  8.95  1.03 11.34
  1.96  0.97  0.39 15.42 21.02 24.59  5.21 21.91  4.04  2.85  5.44  7.16
  4.08  3.64  2.73  3.48  6.12 16.05 12.94  6.08 20.74  8.97  4.18  2.93
  4.06 10.12  4.88  7.25  4.36  1.73  3.11 11.68 15.88 15.03  3.96  1.67
  8.27  7.07 18.69  5.88  8.98  3.77  7.58  4.02  7.31  4.38  3.87  4.68
  7.13 27.98  4.21  7.17  8.54  3.82  0.81  5.22  7.19  4.83  2.96  6.05
  2.72 21.32  7.52  3.68  2.99  7.44  4.55  8.52 21.38  3.25  2.41  6.19
  2.87  8.94 11.81 12.36 11.24  7.24  3.31 11.71 18.95 11.12  0.51 24.91
  0.69 22.71  6.04  9.25  4.34  7.04  1.26  2.54  4.67 12.53  3.09 15.25
  9.01  3.88  5.39  0.48  4.09  5.26  3.27  4.11  5.05  4.53  0.61 11.49
  4.26  3.56 10.08  6.78 19.75  5.03  8.41  4.52  7.01 17.51  7.37  2.51
  0.62  5.68  2.62  7.75  3.92  4.57  5.19 11.54  3.44 19.31  3.13  4.14
  7.14  3.08  3.12  7.57  5.97  4.12  4.44 17.23 22.98  9.15  6.49  7.45

 15.08 22.68  5.96  6.63  5.29  8.73  9.28  4.84 10.48]
hemoglobin_min
[12.9         8.5                nan 14.1         8.6        12.
  9.2         9.9         6.9        10.6        13.2        12.5
  7.7         8.4        13.3        11.7        15.2        11.4
  7.3         9.5        13.8         9.7         5.         12.7
 13.4        10.1        13.9        10.2         9.8         6.5
 10.3         9.         15.8         7.6         8.          9.4
  9.6        12.6         6.4         7.1         7.2        11.8
 10.          7.8         5.3         5.2        11.          9.3
 11.6        10.7        10.8         8.8        13.6         8.7
  8.9        10.9         7.5        11.9        12.3        15.6
 14.6         8.3         7.          8.2         6.8        11.3
 13.5        13.7         5.9        12.4        13.         12.1
  8.1         7.9        14.3        15.9        12.2         7.4
 11.5        11.2        14.2        10.5         9.1        12.8
 11.1        13.1        10.4        14.          4.5        14.8
 17.         16.7        16.3         6.6        15.         15.7
 14.7         4.9         6.7        14.9        15.5        15.1
 14.4         5.4         6.         17.5         5.6        14.5
  3.7        17.4        16.9         6.1         6.3         3.2
  4.2         5.8        15.3         2.4        15.4         4.8
 16.2        16.1         5.5        16.         16.6         3.6
  4.6        16.4         5.7        16.5         6.2         2.
  3.4         3.5        17.2        16.8         4.3        17.1
  4.          4.7         2.6        17.9         3.1         4.1
  5.1         2.8        17.6        19.3        19.4        18.
  2.9        13.5483871   9.35483871  9.67741935 13.38709677 11.29032258
  8.22580645  9.03225806  9.51612903 12.09677419 11.61290323  7.25806452
 12.90322581  8.38709677 13.22580645 11.12903226  6.93548387 13.06451613
  7.74193548  8.5483871   9.19354839  8.70967742  7.58064516 12.58064516
 10.96774194 10.32258065 10.16129032 10.64516129 11.93548387 11.4516129
 14.03225806 13.87096774 14.19354839 12.25806452 16.12903226  7.41935484
 11.77419355 12.41935484  9.83870968 10.48387097 14.51612903 10.80645161
 13.70967742  8.87096774  6.61290323  7.09677419 12.74193548 19.67741935
  4.83870968  8.06451613 15.32258065 15.          7.90322581 14.35483871
 14.83870968  5.64516129 16.4516129   5.96774194  5.48387097 14.67741935
  2.09677419  4.35483871 15.80645161  6.4516129   6.77419355 15.16129032
 15.96774194 15.64516129  5.80645161  4.19354839  0.48387097  5.32258065
 16.61290323 17.25806452  0.64516129  3.38709677  6.29032258 16.29032258
  6.12903226  3.06451613 15.48387097  5.16129032 20.16129032 17.09677419
 17.74193548  4.67741935  4.51612903 16.93548387  3.87096774  2.58064516
 24.83870968  4.03225806 17.58064516 16.77419355  2.25806452 18.5483871
 17.41935484  3.8         3.         17.3         3.3        20.4
 18.6        17.8        17.7         2.1         2.7         4.4
 18.5        18.1        18.3         3.9         1.9         2.2
 19.6         2.5        19.5        18.8         1.8        18.7
 19.         18.2        19.2        18.4        19.1        21.5
 18.9        19.9        11.88       22.4         7.81        1.4
 20.1         2.3        20.7        20.          1.3        21.3       ]
outcome_group
[5. 1.]
database_flag
['MIMIC' 'AUMC' 'eICU' 'PLAGH' 'HJ23']

In [7]:
bestvsworst_df['gender'].replace('U',np.nan,inplace=True)
bestvsworst_df['gender'].replace('1',1,inplace=True)
bestvsworst_df['gender'].replace('0',0,inplace=True)
bestvsworst_df['gender'].unique()

array([ 1.,  0., nan])

In [8]:
bestvsworst_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78830 entries, 0 to 78829
Data columns (total 11 columns):
gender                  78645 non-null float64
age_group               78830 non-null object
unittype                78830 non-null object
admission_type          78702 non-null object
cardiac_surgery_flag    78830 non-null float64
sodium_max              73915 non-null float64
creatinine_max          73544 non-null float64
lactate_max             23191 non-null float64
hemoglobin_min          73184 non-null float64
outcome_group           78830 non-null float64
database_flag           78830 non-null object
dtypes: float64(7), object(4)
memory usage: 6.6+ MB

In [9]:
bestvsworst_df['outcome_group'].replace(1,'Best',inplace=True)
bestvsworst_df['outcome_group'].replace(5,'Worst',inplace=True)

In [10]:
columns=['gender',
         'age_group',
         'unittype',
         'admission_type',
         'cardiac_surgery_flag',
        'sodium_max',
         'creatinine_max',
         'lactate_max',
         'hemoglobin_min',
         'database_flag']
categorical=['gender',
             'age_group',
             'unittype',
             'admission_type',
             'cardiac_surgery_flag',
             'database_flag']
groupby=['outcome_group']
nonnormal=['sodium_max','creatinine_max','lactate_max','hemoglobin_min']
mytable=TableOne(bestvsworst_df,columns,categorical,groupby,nonnormal,pval=True)
print(mytable)

                                  Grouped by outcome_group
                                                   Missing                 Best                Worst P-Value            Test
n                                                                         62027                16803
gender               0.0                               185         27760 (44.8)          7252 (43.3)  <0.001     Chi-squared
                     1.0                                           34142 (55.2)          9491 (56.7)
age_group            (17, 39]                            0          9783 (15.8)           1135 (6.8)  <0.001     Chi-squared
                     (39, 49]                                       8054 (13.0)           1181 (7.0)
                     (49, 59]                                      12203 (19.7)          2454 (14.6)
                     (59, 69]                                      13158 (21.2)          3685 (21.9)
                     (69, 79]                                      10504 (16.9)          4079 (24.3)
                     (79, 300]                                      8325 (13.4)          4269 (25.4)
unittype             CCU                                 0           5066 (8.2)          2168 (12.9)  <0.001     Chi-squared
                     CCU-CTICU                                       2096 (3.4)            581 (3.5)
                     CSICU                                           2682 (4.3)            362 (2.2)
                     CSRU                                            1712 (2.8)            199 (1.2)
                     CTICU                                            731 (1.2)            138 (0.8)
                     EICU                                             489 (0.8)            541 (3.2)
                     KICU                                              60 (0.1)            183 (1.1)
                     MICU                                           9034 (14.6)          3110 (18.5)
                     Med-Surg ICU                                  19857 (32.0)          4229 (25.2)
                     NICU                                            2235 (3.6)            744 (4.4)
                     NSICU                                          8815 (14.2)            328 (2.0)
                     RICU                                             107 (0.2)            464 (2.8)
                     SICU                                           7552 (12.2)          3257 (19.4)
                     SICU&MICU                                         30 (0.0)             50 (0.3)
                     TICU                                             298 (0.5)             63 (0.4)
                     TSICU                                           1263 (2.0)            386 (2.3)
admission_type       ELECTIVE                          128         22275 (36.0)          2211 (13.2)  <0.001     Chi-squared
                     EMERGENCY                                     39626 (64.0)         14590 (86.8)
cardiac_surgery_flag 0.0                                 0         55017 (88.7)         15941 (94.9)  <0.001     Chi-squared
                     1.0                                            7010 (11.3)            862 (5.1)
sodium_max                                            4915  140.0 [137.2,142.0]  141.0 [137.0,145.0]  <0.001  Kruskal-Wallis
creatinine_max                                        5286        0.9 [0.7,1.2]        1.5 [0.9,2.5]  <0.001  Kruskal-Wallis
lactate_max                                          55639        1.8 [1.2,2.9]        4.1 [2.1,8.4]  <0.001  Kruskal-Wallis
hemoglobin_min                                        5646     11.8 [10.1,13.3]      10.1 [8.3,12.0]  <0.001  Kruskal-Wallis
database_flag        AUMC                                0           5024 (8.1)          1929 (11.5)  <0.001     Chi-squared
                     HJ23                                             907 (1.5)            619 (3.7)
                     MIMIC                                          8927 (14.4)          2919 (17.4)
                     PLAGH                                         14943 (24.1)          3743 (22.3)
                     eICU                                          32226 (52.0)          7593 (45.2)
[1] Warning, Hartigan's Dip Test reports possible multimodal distributions for: creatinine_max, hemoglobin_min, lactate_max, sodium_max.
[2] Warning, Tukey test indicates far outliers in: creatinine_max, hemoglobin_min, lactate_max, sodium_max.
[3] Warning, test for normality reports non-normal distributions for: creatinine_max, hemoglobin_min, lactate_max, sodium_max.

In [11]:
bestvsworst_df['age_group'].replace('(17, 39]',0,inplace=True)
bestvsworst_df['age_group'].replace('(39, 49]',1,inplace=True)
bestvsworst_df['age_group'].replace('(49, 59]',2,inplace=True)
bestvsworst_df['age_group'].replace('(59, 69]',3,inplace=True)
bestvsworst_df['age_group'].replace('(69, 79]',4,inplace=True)
bestvsworst_df['age_group'].replace('(79, 300]',5,inplace=True)

bestvsworst_df['unittype'].replace('Med-Surg ICU','MedSurgICU',inplace=True)
bestvsworst_df['unittype'].replace('CCU-CTICU','CCUCTICU',inplace=True)
bestvsworst_df['unittype'].replace('SICU&MICU','SICUMICU',inplace=True)

In [12]:
# encoding
data_type1 = bestvsworst_df
names_dummies = ['age_group', 'unittype', 'admission_type', 'database_flag','gender']
for i in range(len(names_dummies)):
  vars()['dummies_' + names_dummies[i]] = pd.get_dummies(data_type1[names_dummies[i]], prefix=names_dummies[i])
  data_type1 = pd.concat([data_type1, vars()['dummies_' + names_dummies[i]]], axis=1)
data_type1.drop(names_dummies, axis=1, inplace=True)
data_type1

,cardiac_surgery_flag,sodium_max,creatinine_max,lactate_max,hemoglobin_min,outcome_group,age_group_0,age_group_1,age_group_2,age_group_3,...,unittype_TSICU,admission_type_ELECTIVE,admission_type_EMERGENCY,database_flag_AUMC,database_flag_HJ23,database_flag_MIMIC,database_flag_PLAGH,database_flag_eICU,gender_0.0,gender_1.0
0,0.0,138.0,1.40,2.70,12.9,Worst,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
1,1.0,138.0,0.80,NaN,8.5,Best,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,0.0,142.0,0.60,NaN,NaN,Best,0,0,0,1,...,0,0,1,0,0,1,0,0,1,0
3,0.0,139.0,0.90,NaN,14.1,Best,1,0,0,0,...,0,0,1,0,0,1,0,0,0,1
4,1.0,141.0,1.00,NaN,8.6,Best,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
5,0.0,133.0,0.70,1.50,NaN,Worst,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
6,0.0,140.0,1.20,NaN,12.0,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
7,1.0,138.0,1.00,NaN,9.2,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
8,0.0,143.0,0.80,NaN,9.9,Best,0,0,0,1,...,0,0,1,0,0,1,0,0,0,1
9,0.0,133.0,0.50,NaN,6.9,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
10,1.0,140.0,1.30,2.30,10.6,Best,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
11,0.0,NaN,NaN,NaN,NaN,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
12,0.0,139.0,1.10,NaN,13.2,Best,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
13,0.0,138.0,0.50,NaN,12.5,Worst,0,1,0,0,...,0,0,1,0,0,1,0,0,1,0
14,1.0,146.0,0.60,NaN,7.7,Best,0,1,0,0,...,0,1,0,0,0,1,0,0,1,0
15,1.0,137.0,1.20,NaN,8.4,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,1,0
16,0.0,134.0,0.70,1.70,13.3,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
17,0.0,141.0,0.90,NaN,11.7,Best,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
18,0.0,136.0,1.20,3.50,15.2,Worst,1,0,0,0,...,0,0,1,0,0,1,0,0,0,1
19,0.0,140.0,8.30,NaN,11.4,Best,0,0,0,1,...,0,0,1,0,0,1,0,0,0,1
20,1.0,139.0,1.10,NaN,9.2,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
21,0.0,139.0,5.30,NaN,7.3,Best,1,0,0,0,...,0,0,1,0,0,1,0,0,1,0
22,0.0,144.0,1.00,NaN,9.5,Best,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
23,0.0,141.0,0.80,NaN,13.3,Best,1,0,0,0,...,1,0,1,0,0,1,0,0,0,1
24,0.0,NaN,NaN,NaN,NaN,Best,1,0,0,0,...,0,0,1,0,0,1,0,0,0,1
25,0.0,143.0,0.80,NaN,13.8,Best,0,0,1,0,...,0,1,0,0,0,1,0,0,0,1
26,1.0,136.0,0.90,NaN,9.7,Best,0,1,0,0,...,0,1,0,0,0,1,0,0,0,1
27,0.0,142.0,1.60,15.30,5.0,Worst,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
28,0.0,141.0,0.90,NaN,12.7,Best,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
29,0.0,145.0,0.90,NaN,13.4,Best,0,0,0,1,...,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78800,0.0,135.4,0.50,1.78,14.9,Best,0,0,0,1,...,0,0,1,0,1,0,0,0,1,0
78801,0.0,140.0,2.53,3.41,10.7,Worst,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
78802,0.0,142.0,3.23,NaN,12.5,Best,0,1,0,0,...,0,0,1,0,1,0,0,0,0,1
78803,0.0,143.0,1.02,NaN,14.1,Best,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
78804,0.0,146.0,1.88,NaN,7.1,Best,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
78805,0.0,145.0,7.53,2.41,7.6,Worst,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0
78806,0.0,138.3,0.42,1.14,10.9,Best,0,1,0,0,...,0,0,1,0,1,0,0,0,1,0
78807,0.0,140.6,0.95,2.17,11.6,Best,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
78808,0.0,150.0,1.41,1.72,12.9,Worst,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
78809,0.0,132.0,NaN,4.03,12.4,Worst,0,0,1,0,...,0,0,1,0,1,0,0,0,0,1
78810,0.0,153.0,2.43,9.28,9.9,Best,0,0,0,1,...,0,0,1,0,1,0,0,0,0,1
78811,0.0,141.4,NaN,1.24,14.6,Best,1,0,0,0,...,0,0,1,0,1,0,0,0,0,1
78812,0.0,141.0,1.46,NaN,15.5,Best,0,0,1,0,...,0,0,1,0,1,0,0,0,1,0
78813,0.0,153.0,1.43,4.84,14.3,Worst,0,0,0,1,...,0,0,1,0,1,0,0,0,0,1
78814,0.0,138.0,0.85,1.10,13.1,Best,0,1,0,0,...,0,0,1,0,1,0,0,0,0,1
78815,0.0,158.8,2.83,23.00,13.9,Worst,0,1,0,0,...,0,0,1,0,1,0,0,0,0,1
78816,0.0,142.7,0.68,1.44,11.8,Best,1,0,0,0,...,0,0,1,0,1,0,0,0,1,0
78817,0.0,144.0,0.86,NaN,NaN,Worst,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0
78818,0.0,136.0,2.13,1.90,10.0,Best,0,0,1,0,...,0,0,1,0,1,0,0,0,1,0
78819,0.0,136.1,0.39,1.32,9.7,Best,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0
78820,0.0,142.0,5.50,2.59,14.3,Worst,0,0,0,1,...,0,0,1,0,1,0,0,0,0,1
78821,0.0,128.0,0.55,2.50,11.7,Worst,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0
78822,0.0,148.1,1.21,1.29,11.5,Best,0,0,0,1,...,0,0,1,0,1,0,0,0,0,1
78823,0.0,139.0,5.90,1.85,11.1,Best,0,0,1,0,...,0,0,1,0,1,0,0,0,0,1
78824,0.0,140.6,1.53,2.36,8.3,Best,0,0,0,0,...,0,0,1,0,1,0,0,0,1,0
78825,0.0,140.0,2.87,10.48,6.2,Worst,0,0,1,0,...,0,0,1,0,1,0,0,0,0,1
78826,0.0,155.3,1.60,3.77,9.4,Worst,0,0,0,1,...,0,0,1,0,1,0,0,0,1,0
78827,0.0,138.3,0.68,2.72,15.5,Best,1,0,0,0,...,0,0,1,0,1,0,0,0,0,1
78828,0.0,142.0,0.45,1.49,8.4,Best,0,0,1,0,...,0,0,1,0,1,0,0,0,0,1
78829,0.0,136.3,0.53,1.48,7.7,Best,1,0,0,0,...,0,0,1,0,1,0,0,0,0,1

In [13]:
data_type1.rename(columns={'gender_0.0':'gender_0',
                           'gender_1.0':'gender_1'},inplace=True)
data_type1['outcome_group'].replace('Worst',1,inplace=True)
data_type1['outcome_group'].replace('Best',0,inplace=True)

In [14]:
for column in data_type1.drop('outcome_group',axis=1).columns.values:
    model = sm.GLM.from_formula("outcome_group ~ {}".format(column), family=sm.families.Binomial(), data=data_type1)
    result = model.fit()
    print(result.summary())

NameError: name 'sm' is not defined

In [ ]:
data_type1['sodium_max']=data_type1['sodium_max'].fillna(np.nanmedian(data_type1['sodium_max']))
data_type1['creatinine_max']=data_type1['creatinine_max'].fillna(np.nanmedian(data_type1['creatinine_max']))
data_type1['lactate_max']=data_type1['lactate_max'].fillna(np.nanmedian(data_type1['lactate_max']))
data_type1['hemoglobin_min']=data_type1['hemoglobin_min'].fillna(np.nanmedian(data_type1['hemoglobin_min']))
data_type1.info()

## include the lactate

In [ ]:
feature=''
for column in data_type1.drop(['outcome_group','age_group_0'],axis=1).columns.values:
    feature=feature+column+'+'
    
    
model = sm.GLM.from_formula("outcome_group ~ {}".format(feature[:-1]), family=sm.families.Binomial(), data=data_type1)
result = model.fit()
result.summary()

In [ ]:
result_df=pd.DataFrame(columns=['coef','std_err','p','[0.025','0.975]'])
result_df['coef']=result.params
result_df['std_err']=result.bse
result_df['p']=result.pvalues
result_df['[0.025']=result_df['coef']-1.96*result_df['std_err']
result_df['0.975]']=result_df['coef']+1.96*result_df['std_err']
result_df['OR']=np.exp(result_df['coef'])
result_df['floor']=np.exp(result_df['[0.025'])
result_df['upper']=np.exp(result_df['0.975]'])
result_df['p']=['%.2f'%x for x in result_df['p']]
result_df['OR']=['%.2f'%x for x in result_df['OR']]
result_df['floor']=['%.2f'%x for x in result_df['floor']]
result_df['upper']=['%.2f'%x for x in result_df['upper']]
for item in result_df.index:
    result_df.loc[item,'OR_out']=str(result_df.loc[item,'OR'])+' ({}-{})'.format(str(result_df.loc[item,'floor']),str(result_df.loc[item,'upper']))

result_df

In [ ]:
result_df.to_csv('../report/LR_result_include lactate.csv')

## exclude the lactate(to many missing value)

In [ ]:
feature=''
for column in data_type1.drop(['outcome_group','age_group_0','lactate_max'],axis=1).columns.values:
    feature=feature+column+'+'
    
    
model = sm.GLM.from_formula("outcome_group ~ {}".format(feature[:-1]), family=sm.families.Binomial(), data=data_type1)
result = model.fit()
result.summary()

In [ ]:
result_df=pd.DataFrame(columns=['coef','std_err','p','[0.025','0.975]'])
result_df['coef']=result.params
result_df['std_err']=result.bse
result_df['p']=result.pvalues
result_df['[0.025']=result_df['coef']-1.96*result_df['std_err']
result_df['0.975]']=result_df['coef']+1.96*result_df['std_err']
result_df['OR']=np.exp(result_df['coef'])
result_df['floor']=np.exp(result_df['[0.025'])
result_df['upper']=np.exp(result_df['0.975]'])
result_df['p']=['%.2f'%x for x in result_df['p']]
result_df['OR']=['%.2f'%x for x in result_df['OR']]
result_df['floor']=['%.2f'%x for x in result_df['floor']]
result_df['upper']=['%.2f'%x for x in result_df['upper']]
for item in result_df.index:
    result_df.loc[item,'OR_out']=str(result_df.loc[item,'OR'])+' ({}-{})'.format(str(result_df.loc[item,'floor']),str(result_df.loc[item,'upper']))

result_df

In [ ]:
result_df.to_csv('../report/LR_result_exclude lactate.csv')